# Generated by Django 4.1.7 on 2023-06-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GUITARS', 'Guitars'), ('KEYBOARDS', 'Keyboards'), ('PERCUSSION', 'Percussion'), ('AMPLIFIERS', 'Amplifiers'), ('CABLES', 'Cables')], default='GUITARS', max_length=15),
        ),
    ]
